// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ow3hVs2qgpfN7HjpdxwT1N_RT_DEpig',
    appId: '1:1075293188736:web:b8f5b89f65e3b6e97b6c65',
    messagingSenderId: '1075293188736',
    projectId: 'gen-ai-ed4cb',
    authDomain: 'gen-ai-ed4cb.firebaseapp.com',
    storageBucket: 'gen-ai-ed4cb.firebasestorage.app',
    measurementId: 'G-BCEZ6C4PFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTbKQRn9lS2UyFSZ-eSP1aZumea39G18',
    appId: '1:1075293188736:android:81d0337d006f367a7b6c65',
    messagingSenderId: '1075293188736',
    projectId: 'gen-ai-ed4cb',
    storageBucket: 'gen-ai-ed4cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATfM_Z1pmxrf_lPOYCNhytneJ-cn3VgZw',
    appId: '1:1075293188736:ios:e5d3a401b211dfdf7b6c65',
    messagingSenderId: '1075293188736',
    projectId: 'gen-ai-ed4cb',
    storageBucket: 'gen-ai-ed4cb.firebasestorage.app',
    iosBundleId: 'com.example.smartpostAi',
  );

}